package com.example.cleanarchitecture.core.util

enum class FormErrors {
      MISSING_FIRST_NAME,
      MISSING_LAST_NAME,
      INVALID_FIRST_NAME,
      INVALID_LAST_NAME,
      MISSING_EMAIL,
      INVALID_EMAIL,
      MISSING_PASSWORD,
      MISSING_OLD_PASSWORD,
      INVALID_PASSWORD,
      MISSING_CONFIRM_PASSWORD,
      PASSWORDS_NOT_MATCHING,
      MISSING_PHONE,

      INVALID_PHONE,
   }
